vich_uploader:
    db_driver: orm # orm, mongodb or propel
    storage:    file_system
    mappings:
        product_image:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer:
                service: Vich\UploaderBundle\Naming\SmartUniqueNamer
